apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-storage-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-storage
  template:
    metadata:
      labels:
        app: service-storage
    spec:
      containers:
        - name: service-storage
          image: brucegroverlee/speeky-service-storage
          resources:
            limits:
              memory: 256Mi
              cpu: '1'
            requests:
              memory: 128Mi
              cpu: '0.2'
          env:
            - name: DEBUG
              value: 'server:*'
            - name: NODE_ENV
              value: 'dev'
            - name: PORT
              value: '4000'
            - name: RABBITMQ_URL
              value: 'amqp://rabbit-srv/speeky'
            - name: RABBITMQ_CONNECTION_NAME
              value: 'storage_service'
            - name: RABBITMQ_EXCHANGE
              value: 'event_bus'
            - name: RABBITMQ_EXCHANGE_TYPE
              value: 'topic'
            - name: RABBITMQ_QUEUE
              value: 'storage_service_queue'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './gcp-service-account.json'
            - name: GOOGLE_CLOUD_STORAGE_BUCKET
              value: 'speeky-development'
---
apiVersion: v1
kind: Service
metadata:
  name: service-storage-srv
spec:
  type: NodePort
  selector:
    app: service-storage
  ports:
    - name: service-storage
      protocol: TCP
      port: 4000
      targetPort: 4000
